server:
  port: 80
  servlet:
    context-path: /
myapp:
  pulic-host: 1.116.122.186
spring:
  datasource:
    #内网地址
    url: jdbc:mysql://1.116.122.186:3306/kv?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Hello123!@#

  redis:
    host: 1.116.122.186
    port: 6379
    lettuce:
      pool:
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接
  #  data:
  #    mongodb:
  #      uri: mongodb://zxh:Hello123@116.62.245.234:27017/zxhtest

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML
    suffix: .html  #后缀名
