server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://10.0.24.10:3306/kv?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Hello123!@#
#    url: jdbc:mysql://localhost:3306/kv?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
#    password: 123456
  redis:
    host: 10.0.24.10
#    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 3 #连接池中的最大空闲连接
        min-idle: 3 #连接池中的最小空闲连接
    timeout:

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML
    suffix: .html  #后缀名
